language: php

notifications:
  email:
    on_success: never

git:
  depth: 2

matrix:
  include:
    - php: 7.1
    - php: 7.2
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - composer test-in-ci
